"""empty message

Revision ID: 0500824bacf5
Revises: 77465916f36c
Create Date: 2025-04-26 19:19:14.939320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0500824bacf5'
down_revision = '77465916f36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=648),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=648),
               existing_nullable=False)

    # ### end Alembic commands ###
