"""empty message

Revision ID: 1479f6ca7dec
Revises: 39fb339412e0
Create Date: 2025-06-22 22:49:45.230788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1479f6ca7dec'
down_revision = '39fb339412e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspicious_organization', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('suspicious_user', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.drop_column('suspicious_user')
        batch_op.drop_column('suspicious_organization')

    # ### end Alembic commands ###
