"""empty message

Revision ID: 39fb339412e0
Revises: c98ee452795e
Create Date: 2025-06-22 22:05:27.002838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fb339412e0'
down_revision = 'c98ee452795e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('type_t_or_tor', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.drop_column('type_t_or_tor')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
