"""empty message

Revision ID: b141a3384ecb
Revises: b40f46461594
Create Date: 2025-06-21 17:10:05.044286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b141a3384ecb'
down_revision = 'b40f46461594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.Column('label_name', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('threaten_level', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intelligence')
    # ### end Alembic commands ###
