"""empty message

Revision ID: c98ee452795e
Revises: 4ac63fb5211b
Create Date: 2025-06-21 18:32:44.347868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c98ee452795e'
down_revision = '4ac63fb5211b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('insert_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('label_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
        batch_op.alter_column('area',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
        batch_op.alter_column('threaten_level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.alter_column('threaten_level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
        batch_op.alter_column('area',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
        batch_op.alter_column('label_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
        batch_op.alter_column('insert_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)

    # ### end Alembic commands ###
